name: tag

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

env:
  REGISTRY: docker.io
  REPOSITORY: ${{ secrets.REGISTRY_NAMESPACE }}/mlflow-wine-classifier

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check current folder
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.9' # Specify your Python version
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Check Python version
        run: python --version

      - name: Install mlflow
        run: pip install mlflow[mlserver]

      - name: Check mlflow version
        run: mlflow --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Check Docker version
        run: docker --version
        
      - name: Login to Container Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      #- name: Build Docker image
      #  run: mlflow models build-docker -m runs:/dce3966053da44658dc78889d02ac9d8/model -n ${{ env.REPOSITORY }}:latest --enable-mlserver

      #- name: Push Docker image
      #  run: docker push ${{ env.REPOSITORY }}:latest
